// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRokFMzU4KkwSlqyzKs_ARY90EwRYh0pQ',
    appId: '1:1072277627373:web:099c8dd45f61dc151287e4',
    messagingSenderId: '1072277627373',
    projectId: 'eventify-mobile-b78b5',
    authDomain: 'eventify-mobile-b78b5.firebaseapp.com',
    storageBucket: 'eventify-mobile-b78b5.firebasestorage.app',
    measurementId: 'G-974C3E8YLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBboMX_t0gAebbI5btNIsaNmwASa941yHk',
    appId: '1:1072277627373:android:1164236e82fadf9f1287e4',
    messagingSenderId: '1072277627373',
    projectId: 'eventify-mobile-b78b5',
    storageBucket: 'eventify-mobile-b78b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqB2cdjt67wiw-MmTG7Gu89RRQ-sNOjfY',
    appId: '1:1072277627373:ios:9e49d06adbf4860f1287e4',
    messagingSenderId: '1072277627373',
    projectId: 'eventify-mobile-b78b5',
    storageBucket: 'eventify-mobile-b78b5.firebasestorage.app',
    iosBundleId: 'com.example.eventify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqB2cdjt67wiw-MmTG7Gu89RRQ-sNOjfY',
    appId: '1:1072277627373:ios:9e49d06adbf4860f1287e4',
    messagingSenderId: '1072277627373',
    projectId: 'eventify-mobile-b78b5',
    storageBucket: 'eventify-mobile-b78b5.firebasestorage.app',
    iosBundleId: 'com.example.eventify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRokFMzU4KkwSlqyzKs_ARY90EwRYh0pQ',
    appId: '1:1072277627373:web:18afa92d42f212c31287e4',
    messagingSenderId: '1072277627373',
    projectId: 'eventify-mobile-b78b5',
    authDomain: 'eventify-mobile-b78b5.firebaseapp.com',
    storageBucket: 'eventify-mobile-b78b5.firebasestorage.app',
    measurementId: 'G-8BJEYMPXH3',
  );

}