// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGq_DxzMYt4rfg56Z-IH_N8dv6hfkzMvk',
    appId: '1:456631169941:web:23c208144fad37617a7c9c',
    messagingSenderId: '456631169941',
    projectId: 'eventify-mobile',
    authDomain: 'eventify-mobile.firebaseapp.com',
    storageBucket: 'eventify-mobile.firebasestorage.app',
    measurementId: 'G-XFWEV6FDYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwFrWk8UbXYL-l6SIxpp1GrCPBkcucvI8',
    appId: '1:456631169941:android:5faa845827abedd47a7c9c',
    messagingSenderId: '456631169941',
    projectId: 'eventify-mobile',
    storageBucket: 'eventify-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9lqxmstg_ua9RT3behXyginyW8W1FxTY',
    appId: '1:456631169941:ios:57052ad2c71b159b7a7c9c',
    messagingSenderId: '456631169941',
    projectId: 'eventify-mobile',
    storageBucket: 'eventify-mobile.firebasestorage.app',
    iosBundleId: 'com.example.eventify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9lqxmstg_ua9RT3behXyginyW8W1FxTY',
    appId: '1:456631169941:ios:57052ad2c71b159b7a7c9c',
    messagingSenderId: '456631169941',
    projectId: 'eventify-mobile',
    storageBucket: 'eventify-mobile.firebasestorage.app',
    iosBundleId: 'com.example.eventify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGq_DxzMYt4rfg56Z-IH_N8dv6hfkzMvk',
    appId: '1:456631169941:web:4665b21016bf1fce7a7c9c',
    messagingSenderId: '456631169941',
    projectId: 'eventify-mobile',
    authDomain: 'eventify-mobile.firebaseapp.com',
    storageBucket: 'eventify-mobile.firebasestorage.app',
    measurementId: 'G-3W3MT0Z0H0',
  );
}
